---

functional:
  Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
  Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.

nonfunctional:
  Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  Сайт должен быть безопасным и защищать данные пользователя.
  Сайт должен иметь мобильную версию.
  Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  Сайт должен быть способен обрабатывать большое количество трафика.
  Сайт должен быть доступен на различных устройствах.
  
implicit:
  На сайте должна быть форма обратной связи с call-центром/ботом.
  Должна быть возможность создать Личный кабинет пользователя.
  Должна быть система оценок товаров пользователями с возможностью оставить отзыв о товаре.
  Должна быть сортировка товаров по  - популярности, цене, релевантности.
  У сайта должны быть узнаваемые элементы веб-дизайна - фирменные цвета, логотип, иконка, шрифты и прочее.
  
  
