---
- summary: |
    Проверка кнопки переключения языков
  status: pass
   
- summary: |
    Проверка переключения языка интерфейса на русский
  status: fail

- summary: |
    Проверка переключения языка интерфейса на английский
  status: pass

- summary: |
    Проверка автоматического сворачивания выпадающего меню выбора языка
  status: fail

- summary: |
    Проверка подтверждения добавления товаров в Корзину 
  status: fail

- summary: |
    Проверка закрытия окна подтверждения Заказа крестиком
  status: fail

- summary: |
    Проверка очистки Корзины после оформления заказа
  status: fail
